drop table learners;
drop table schools;


CREATE TABLE schools
(
    id integer NOT NULL primary key generated by default as identity,
    nameSchool text NOT NULL,
    city text NOT NULL
);

insert into schools (nameSchool, city)
    values
    ('Средняя школа №1', 'Ульяновск'),
    ('Средняя школа №2', 'Ульяновск'),
    ('Восьмилетняя школа №3', 'Ульяновск');


CREATE TABLE learners
(
    id integer primary key generated by default as identity,
    fullName text NOT NULL,
    dateBirth text NOT NULL,
    numberTelf text NOT NULL,
    school_id integer,
    foreign key (school_id) references schools (id)
);

insert into learners (fullName, dateBirth, numberTelf, school_id)
    values
    ('Иванов Петр Ильич', '01.01.1997', '89061427968' , 1),
    ('Борисов Дмитрий Анатольевич', '05.02.1997', '89061427969' , 2),
    ('Петров Василий Иванович', '11.11.1997', '89061427964' , 3);
